### ISSUE TITLE
Unable to search for some terms which might be frequently said

### ISSUE THREAD

**Issue by devins2518** [jasons-gh/the-chomsky-index#2]
I'd like to first thank you for making this tool! Moving on, searching for terms like "america" has a much longer search time and sometimes crashes unlike terms like "climate" or "haiti". This might be because it is mentioned frequently in multiple files and the `re` library for python being generally slow. [It might be worth it to look into using this library to see if it can improve performance somewhat.](https://github.com/xysun/regex) Another option might be to completely switch away from python which will generally have worse performance in these high IO tasks than a low level language like C(++) or Rust. Once again, thanks for making this tool, I hope it becomes quite popular 😄!

**Comment by jasons-gh** [comment]
Hi, from my testing, there are two things that take the most time for this program: the regex search and PyQt5 clearing previous results. For extremely common words, a lot of time will be spent on the regex, and possibly more on clearing. I'm not familiar with that library but will have a look - it would require some testing and verification that it gives the same results as re.

Since the two parts that take the longest are not I/O operations (opening the 2000+ files is suprisingly fast), I don't think there would be much improvement in performance by switching to a low-level language.

And by the way you're welcome, thank you for using this! :)
